<?php
// Final optimized form submission for cPanel - no PHPMailer dependency
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Check if form was submitted
if ($_SERVER['REQUEST_METHOD'] === 'POST' && !empty($_POST)) {
    
    // Email configuration
    $to = 'johndavid78663@gmail.com'; // Change this to your email address
    $subject = isset($_POST['subject']) ? $_POST['subject'] : 'New Form Submission from ' . $_SERVER['SERVER_NAME'];
    
    // Build the email content with beautiful HTML template
    $emailContent = '
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Form Submission</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 600px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f4f4f4;
            }
            .email-container {
                background-color: #ffffff;
                border-radius: 10px;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                overflow: hidden;
            }
            .header {
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                padding: 30px;
                text-align: center;
            }
            .header h1 {
                margin: 0;
                font-size: 24px;
                font-weight: 300;
            }
            .content {
                padding: 30px;
            }
            .field-list {
                list-style: none;
                padding: 0;
                margin: 0;
            }
            .field-item {
                background-color: #f8f9fa;
                border-left: 4px solid #667eea;
                margin-bottom: 15px;
                padding: 15px;
                border-radius: 5px;
            }
            .field-label {
                font-weight: bold;
                color: #495057;
                margin-bottom: 5px;
                text-transform: capitalize;
            }
            .field-value {
                color: #6c757d;
                word-wrap: break-word;
            }
            .footer {
                background-color: #f8f9fa;
                padding: 20px 30px;
                text-align: center;
                color: #6c757d;
                font-size: 14px;
            }
            .timestamp {
                background-color: #e9ecef;
                padding: 10px;
                border-radius: 5px;
                margin-top: 20px;
                text-align: center;
                font-size: 12px;
                color: #6c757d;
            }
        </style>
    </head>
    <body>
        <div class="email-container">
            <div class="header">
                <h1>📧 New Form Submission</h1>
                <p>You have received a new form submission from your website</p>
            </div>
            
            <div class="content">
                <h2>📋 Form Details</h2>
                <ul class="field-list">';
    
    // Loop through all POST fields and create list items
    foreach ($_POST as $field_name => $field_value) {
        // Skip empty values
        if (empty($field_value) && $field_value !== '0') {
            continue;
        }
        
        // Clean and format field name for display
        $display_name = ucwords(str_replace(['_', '-'], ' ', $field_name));
        
        // Handle different field types
        if (is_array($field_value)) {
            $field_value = implode(', ', $field_value);
        }
        
        // Sanitize the value for HTML output
        $field_value = htmlspecialchars($field_value, ENT_QUOTES, 'UTF-8');
        
        $emailContent .= '
                    <li class="field-item">
                        <div class="field-label">' . $display_name . '</div>
                        <div class="field-value">' . $field_value . '</div>
                    </li>';
    }
    
    $emailContent .= '
                </ul>
                
                <div class="timestamp">
                    <strong>📅 Submitted on:</strong> ' . date('F j, Y \a\t g:i A T') . '<br>
                    <strong>🌐 From:</strong> ' . $_SERVER['SERVER_NAME'] . '<br>
                    <strong>📱 User Agent:</strong> ' . (isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : 'Not available') . '
                </div>
            </div>
            
            <div class="footer">
                <p>This email was automatically generated by your website contact form.</p>
                <p>© ' . date('Y') . ' ' . $_SERVER['SERVER_NAME'] . ' - All rights reserved</p>
            </div>
        </div>
    </body>
    </html>';
    
    // Get the domain name for proper From address
    $domain = $_SERVER['SERVER_NAME'];
    
    // Try multiple From address formats for better compatibility
    $from_addresses = [
        'noreply@' . $domain,
        'webmaster@' . $domain,
        'info@' . $domain,
        'admin@' . $domain
    ];
    
    $mail_sent = false;
    $error_message = '';
    $successful_from = '';
    
    // Try each From address until one works
    foreach ($from_addresses as $from_email) {
        // Email headers for HTML email - optimized for cPanel
        $headers = array(
            'MIME-Version: 1.0',
            'Content-type: text/html; charset=UTF-8',
            'From: ' . $from_email,
            'Reply-To: ' . $from_email,
            'Return-Path: ' . $from_email,
            'X-Mailer: PHP/' . phpversion(),
            'X-Priority: 3',
            'X-MSMail-Priority: Normal'
        );
        
        // Try to send email
        $result = mail($to, $subject, $emailContent, implode("\r\n", $headers));
        
        if ($result) {
            $mail_sent = true;
            $successful_from = $from_email;
            break;
        } else {
            $error_message .= "Failed with From: $from_email\n";
        }
    }
    
    // Log the attempt for debugging
    $log_message = date('Y-m-d H:i:s') . " - Email attempt to $to - Status: " . ($mail_sent ? 'SUCCESS' : 'FAILED') . " - From: " . ($successful_from ?: 'NONE') . "\n";
    error_log($log_message, 3, 'email_log.txt');
    
    // Return JSON response
    header('Content-Type: application/json');
    
    if ($mail_sent) {
        echo json_encode([
            'status' => 'success',
            'to' => $to,
            'from' => $successful_from,
            'message' => 'Form submitted successfully! We will get back to you soon.',
            'timestamp' => date('Y-m-d H:i:s')
        ]);
    } else {
        echo json_encode([
            'status' => 'error',
            'message' => 'Failed to send email. Please try again later.',
            'timestamp' => date('Y-m-d H:i:s'),
            'debug_info' => [
                'to' => $to,
                'subject' => $subject,
                'domain' => $domain,
                'mail_function' => function_exists('mail') ? 'Available' : 'Not Available',
                'error_details' => $error_message
            ]
        ]);
    }
    
} else {
    // No POST data or invalid request
    header('Content-Type: application/json');
    echo json_encode([
        'status' => 'error',
        'message' => 'Invalid request method or no form data received.',
        'timestamp' => date('Y-m-d H:i:s'),
        'debug_info' => [
            'post_data' => $_POST,
            'request_method' => $_SERVER['REQUEST_METHOD']
        ]
    ]);
}
?>
